# Étape 1 : Utiliser une image Node.js pour le développement
FROM node:16-alpine

# Définir le répertoire de travail
WORKDIR /app

# Copier uniquement les fichiers de dépendances pour installer plus vite
COPY package.json package-lock.json* ./

# Installer les dépendances
RUN npm install

# Copier tout le code source
COPY . .

# Créer le répertoire de cache avec les bonnes permissions
RUN mkdir -p /app/node_modules/.cache && chmod -R 777 /app/node_modules/.cache

# Exposer le port utilisé par l'app (par exemple React utilise 3000)
EXPOSE 3000

# Lancer le serveur de développement
CMD ["npm", "start"]